services:
  pytorch:
    image: pytorch/pytorch:latest
    container_name: pytorch_container
    volumes:
      - ./digit_recognition:/workspace/digit_recognition
      - ./disease_detection:/workspace/disease_detection
      - ./pet_classification:/workspace/pet_classification
      - ./wildlife_detection:/workspace/wildlife_detection
    ports:
      - "8888:8888"
    command: >
      jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root
    environment:
      - JUPYTER_TOKEN=test-token
